# Generated by Django 6.0.5 on 2026-05-13 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('credit_score', models.IntegerField()),
                ('monthly_salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HierarchyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=50)),
                ('level_rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_code', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('hire_date', models.DateField()),
                ('hierarchy_level_id', models.IntegerField()),
                ('territory_id', models.IntegerField()),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('resigned', 'Resigned')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Transferred', 'Transferred'), ('Terminated', 'Terminated')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceApplication',
            fields=[
                ('finance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('requested_amount', models.FloatField()),
                ('approved_amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disbursed_amount', models.FloatField()),
                ('interest_rate', models.FloatField()),
                ('loan_status', models.CharField(choices=[('Active', 'Active'), ('Closed', 'Closed'), ('Delayed', 'Delayed')], max_length=20)),
                ('dpd_count', models.IntegerField(default=0)),
                ('finance_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.financeapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('installment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('due_date', models.DateField()),
                ('total_amount', models.FloatField()),
                ('paid_amount', models.FloatField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Partial', 'Partial'), ('Overdue', 'Overdue')], max_length=20)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loan')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.territory')),
            ],
        ),
    ]
