# Generated by Django 6.0.5 on 2026-05-14 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hierarchy_level_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.hierarchylevel'),
        ),
    ]
