# Generated by Django 6.0.5 on 2026-05-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employee_hierarchy_level_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='territory_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.territory'),
        ),
    ]
