# Generated by Django 6.0.5 on 2026-05-15 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customer_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commision',
            fields=[
                ('commision_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loan')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeKPI',
            fields=[
                ('kpi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('target_amount', models.FloatField()),
                ('achieved_amount', models.FloatField()),
                ('calculation_month', models.DateField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
        ),
    ]
