# Generated by Django 6.0.5 on 2026-05-15 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_commision_employeekpi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commision',
            old_name='commision_id',
            new_name='commission_id',
        ),
    ]
