# Generated by Django 6.0.5 on 2026-05-15 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_commision_id_commision_commission_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commision',
            new_name='Commission',
        ),
    ]
