# Generated by Django 6.0.5 on 2026-05-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_commision_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerassignment',
            name='id',
        ),
        migrations.AddField(
            model_name='customerassignment',
            name='assignment_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
