# Generated by Django 6.0.5 on 2026-05-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_customerassignment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeekpi',
            name='collection_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
