# Generated by Django 6.0.5 on 2026-05-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_employeekpi_collection_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
