# Generated by Django 6.0.5 on 2026-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_customer_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='installment_amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='outstanding_balance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
