# Generated by Django 6.0.5 on 2026-05-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_loan_installment_amount_loan_outstanding_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='tenure',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
